#!/bin/bash

restart() {
	clear
	cargo shuttle project restart --idle-minutes 0
	cargo shuttle deploy --no-test --working-directory h4bot --allow-dirty
}

deploy() {
	clear
	cargo shuttle deploy --allow-dirty
}

help() {
	echo "Usage: run [restart|deploy]"
}

case "$1" in
restart) restart ;;
deploy) deploy ;;
*) help ;;
esac